export const STARTING_CREDIT_BALANCE = 25;
export const CONTACT_UNLOCK_COST = 5;
export const CONTACT_ACCESS_WINDOW_DAYS = 30;
export const CONTACT_ACCESS_WINDOW_MS = CONTACT_ACCESS_WINDOW_DAYS * 24 * 60 * 60 * 1000;
