import {
  ArrowRight, BadgeCheck, Bot, Check, Database, FileBarChart, Globe2,
  FolderKanban, Inbox, MapPin, Search, Sparkles, Upload, Users, Workflow,
} from "lucide-react";
import type { AppRoute } from "../hooks/useRoute";
import { Logo } from "./Logo";
import "./LandingPage.css";

const products = [
  { number: "01", icon: Database, name: "Creatorly Discovery", title: "Find creators in India and beyond.", body: "Search Instagram, YouTube, and Facebook profiles by category, audience size, and location. Compare supplied metrics and save the best fits to your workspace.", points: ["India-first, global creator search", "Profiles from 1K followers", "Audience and engagement metrics"], visual: "discovery" as const },
  { number: "02", icon: Users, name: "Private creator CRM", title: "Keep every creator relationship in one place.", body: "Save Creatorly profiles beside creators your team adds. Track contacts, owners, stages, and next steps in one private workspace.", points: ["CSV upload and manual entry", "Private workspace contacts", "Stages, owners, notes, and next actions"], visual: "crm" as const },
  { number: "03", icon: Globe2, name: "Chrome extension", title: "Save creators while you browse.", body: "Match social profiles, check if they are already saved, unlock available contacts, and add new profiles to your workspace.", points: ["Shows the connected workspace", "Detects already-saved creators", "Saves matched and private profiles"], visual: "extension" as const },
  { number: "04", icon: FolderKanban, name: "Campaign workspace", title: "Run campaigns from brief to report.", body: "Organise campaigns by client or brand, add creators, track content and approvals, and export clear reports.", points: ["Client and division grouping", "Creator pipeline and deliverables", "Review access and scoped reports"], visual: "campaign" as const },
] as const;

const addons = [
  { icon: Bot, title: "AI Agents", body: "Agents that help build shortlists, research contacts, and prepare campaign work." },
  { icon: Inbox, title: "Unified Inbox", body: "Creator conversations and replies connected to the campaign record." },
  { icon: Workflow, title: "Automations", body: "Controlled follow-ups, handoffs, reminders, and repetitive campaign actions." },
  { icon: FileBarChart, title: "Connected reporting", body: "Live performance reporting from connected social and outreach channels." },
] as const;

function ProductVisual({ type, onContinue }: { type: typeof products[number]["visual"]; onContinue(): void }) {
  if (type === "discovery") return <div className="product-ui discovery-ui"><div className="ui-search"><Search size={16}/><span>wellness creators in Mumbai</span><kbd>Search</kbd></div><div className="ui-filters"><span>Instagram</span><span>1K–10K</span><span className="selected">Imported</span></div><div className="ui-table"><div className="ui-table-head"><span>Creator</span><span>Audience</span><span>Contact</span></div>{[["MK","Maya Kapoor","9.8K","Pending"],["AM","Aanchal Mehta","6.4K","Pending"],["NK","Noor Khan","2.9K","Pending"]].map(row => <div className="ui-row" key={row[1]}><span className="ui-person"><i>{row[0]}</i><b>{row[1]}</b></span><strong>{row[2]}</strong><em>{row[3]}</em></div>)}</div></div>;
  if (type === "crm") return <div className="product-ui crm-ui"><header><div><span>Creator CRM</span><strong>248 creators</strong></div><button type="button" onClick={onContinue}><Upload size={14}/> Add creators</button></header><div className="crm-columns"><span>Creator</span><span>Source</span><span>Stage</span></div>{[["RS","Riya Shah","Creatorly data","Contacted"],["AV","Aarav Verma","Uploaded by your team","Negotiating"],["NS","Nisha Sen","Added manually","Shortlisted"]].map(row => <div className="crm-preview-row" key={row[1]}><span className="ui-person"><i>{row[0]}</i><b>{row[1]}</b></span><em>{row[2]}</em><strong>{row[3]}</strong></div>)}</div>;
  if (type === "extension") return <div className="product-ui browser-ui"><div className="browser-address"><span/><span/><span/><p>instagram.com/maya_creates</p></div><div className="social-profile"><i>MK</i><strong>Maya Kapoor</strong><small>Wellness creator · Mumbai</small></div><aside><header><Logo/><span>Connected</span></header><small>QA Agency workspace</small><div className="match-state"><BadgeCheck size={16}/><span><b>Profile matched</b><small>Already saved to Creator CRM</small></span></div><button type="button" onClick={onContinue}>Open saved creator <ArrowRight size={14}/></button></aside></div>;
  return <div className="product-ui campaign-ui"><header><span>Campaigns</span><button type="button" onClick={onContinue}>+ Create campaign</button></header><div className="campaign-tabs"><span>All campaigns <b>8</b></span><span className="selected">Northstar Foods <b>3</b></span><span>Aperture Labs <b>2</b></span></div><div className="campaign-card-preview"><small>Northstar Foods</small><strong>Festive creator launch</strong><p>Drive consideration with trusted lifestyle creators.</p><footer><span><Users size={13}/> 12 creators</span><span>INR 500,000</span></footer></div></div>;
}

export function LandingPage({ navigate }: { navigate(route: AppRoute): void }) {
  const startFree = () => navigate({ name: "signup" });
  const continueFromPreview = () => navigate({ name: "signup", reason: "workspace" });
  return <main className="home-page">
    <header className="home-nav"><Logo/><nav aria-label="Landing navigation"><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#addons">Add-ons</a><button onClick={() => navigate({ name: "pricing" })}>Pricing</button></nav><div className="home-nav-actions"><button className="text-button" onClick={() => navigate({ name: "login" })}>Log in</button><button className="button button-primary" onClick={startFree}>Start free</button></div></header>
    <section className="home-hero" aria-labelledby="home-title"><div className="home-hero-copy"><p className="home-kicker"><Sparkles size={14}/> Built for Indian brands and agencies</p><h1 id="home-title"><span>Start in India.</span> Reach creators everywhere.</h1><p>Find the right creators, keep every relationship organised, and run campaigns from first shortlist to final report.</p><div className="home-market-note"><MapPin size={15}/><span><strong>India-first discovery</strong><small>Global creator reach when your brief needs it</small></span></div><div className="home-hero-actions"><button className="button button-primary" onClick={startFree}>Start free <ArrowRight size={17}/></button><a href="#workflow">See how it works</a></div><div className="home-trust"><span><Check size={14}/> 25 credits included</span><span><Check size={14}/> No card needed</span><span><Check size={14}/> Private workspace</span></div></div><div className="home-operating-rail" aria-label="Creatorly product workflow"><header><span>Your campaign path</span><small><i/> Ready to start</small></header><div className="operating-path" aria-hidden="true"/>{products.map(({ number, icon: Icon, name }, index) => <div className={`operating-step ${index === 0 ? "is-current" : ""}`} key={name}><code>{number}</code><span><Icon size={17}/></span><strong>{name}</strong><small>{index === 0 ? "Search" : index === 1 ? "Save" : index === 2 ? "Reach" : "Launch"}</small>{index < products.length - 1 ? <ArrowRight size={15}/> : <BadgeCheck size={16}/>}</div>)}<footer><span><b>12</b> shortlisted</span><span><b>8</b> contacted</span><span><b>4</b> in review</span><span><b>3</b> live</span></footer></div></section>
    <section className="home-audience" aria-label="Built for Indian creator teams"><p>Built for India. Ready for global creator work.</p><div><span>Indian agencies</span><span>Indian brands</span><span>Global creator reach</span><span>Talent teams</span></div></section>
    <section className="home-products" id="platform"><header className="home-section-head"><p className="eyebrow">What you can do</p><h2>Everything your creator team needs.</h2><p>Find creators, save relationships, and keep every campaign moving in one place.</p></header>{products.map(({ number, icon: Icon, name, title, body, points, visual }, index) => <article className={`home-product-row ${index % 2 ? "reverse" : ""}`} id={index === 0 ? "workflow" : undefined} key={name}><div className="home-product-copy"><span className="product-number">{number}</span><div className="product-name"><Icon size={18}/>{name}</div><h3>{title}</h3><p>{body}</p><ul>{points.map(point => <li key={point}><Check size={14}/>{point}</li>)}</ul></div><div className="home-product-stage"><ProductVisual type={visual} onContinue={continueFromPreview}/></div></article>)}</section>
    <section className="home-addons" id="addons"><header><div><p className="eyebrow">Coming later</p><h2>More tools are on the way.</h2></div><p>These features are planned and are not live yet.</p></header><div>{addons.map(({ icon: Icon, title, body }) => <article key={title}><span><Icon size={19}/></span><div><small>Planned</small><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
    <section className="home-final"><span><FolderKanban size={18}/> Start your creator workspace</span><h2>Run your next campaign in one place.</h2><p>Start free with the tools available today.</p><button className="button" onClick={startFree}>Start free <ArrowRight size={18}/></button></section>
    <footer className="home-footer"><Logo/><span>© 2026 Creatorly · Built for Indian creator teams</span><nav aria-label="Footer navigation"><a href="#platform">Platform</a><a href="#addons">Planned features</a><button onClick={() => navigate({ name: "pricing" })}>Pricing</button></nav></footer>
  </main>;
}
