import {
  ArrowRight, BadgeCheck, Bot, Check, Database, FileBarChart, Globe2,
  FolderKanban, Inbox, Search, Sparkles, Upload, Users, Workflow,
} from "lucide-react";
import type { AppRoute } from "../hooks/useRoute";
import { Logo } from "./Logo";
import "./LandingPage.css";

const products = [
  { number: "01", icon: Database, name: "Creatorly Discovery", title: "Find creators with the audience, market, and contact access your brief needs.", body: "Search Creatorly’s own creator database by platform, category, audience size, location, and verification state. Save the strongest profiles directly to your workspace.", points: ["Search across major social platforms", "Filter by audience and market", "Unlock verified partnership contacts"], visual: "discovery" as const },
  { number: "02", icon: Users, name: "Private creator CRM", title: "Build a creator network your team owns and can actually use.", body: "Keep Creatorly profiles beside private creators your team uploads or adds manually. Track every relationship without changing Creatorly’s shared database.", points: ["CSV upload and manual entry", "Private workspace contacts", "Stages, owners, notes, and next actions"], visual: "crm" as const },
  { number: "03", icon: Globe2, name: "Chrome extension", title: "Research creators in the browser, then save them to the right workspace.", body: "Match supported social profiles, see whether a creator is already saved, unlock available contact data, and add unmatched profiles privately.", points: ["Shows the connected workspace", "Detects already-saved creators", "Saves matched and private profiles"], visual: "extension" as const },
  { number: "04", icon: FolderKanban, name: "Campaign workspace", title: "Move from a shortlist to live content without rebuilding the work elsewhere.", body: "Group campaigns by client or internal division, assign creators, track deliverables and approvals, and export reports for the people who need them.", points: ["Client and division grouping", "Creator pipeline and deliverables", "Review access and scoped reports"], visual: "campaign" as const },
] as const;

const addons = [
  { icon: Bot, title: "AI Agents", body: "Agents that help build shortlists, research contacts, and prepare campaign work." },
  { icon: Inbox, title: "Unified Inbox", body: "Creator conversations and replies connected to the campaign record." },
  { icon: Workflow, title: "Automations", body: "Controlled follow-ups, handoffs, reminders, and repetitive campaign actions." },
  { icon: FileBarChart, title: "Connected reporting", body: "Live performance reporting from connected social and outreach channels." },
] as const;

function ProductVisual({ type }: { type: typeof products[number]["visual"] }) {
  if (type === "discovery") return <div className="product-ui discovery-ui"><div className="ui-search"><Search size={16}/><span>wellness creators in Mumbai</span><kbd>Search</kbd></div><div className="ui-filters"><span>Instagram</span><span>100K–1M</span><span className="selected">Verified</span></div><div className="ui-table"><div className="ui-table-head"><span>Creator</span><span>Audience</span><span>Contact</span></div>{[["MK","Maya Kapoor","842K","3 available"],["AM","Aanchal Mehta","416K","2 available"],["NK","Noor Khan","291K","1 available"]].map(row => <div className="ui-row" key={row[1]}><span className="ui-person"><i>{row[0]}</i><b>{row[1]}</b></span><strong>{row[2]}</strong><em>{row[3]}</em></div>)}</div></div>;
  if (type === "crm") return <div className="product-ui crm-ui"><header><div><span>Creator CRM</span><strong>248 creators</strong></div><button><Upload size={14}/> Add creators</button></header><div className="crm-columns"><span>Creator</span><span>Source</span><span>Stage</span></div>{[["RS","Riya Shah","Creatorly data","Contacted"],["AV","Aarav Verma","Uploaded by your team","Negotiating"],["NS","Nisha Sen","Added manually","Shortlisted"]].map(row => <div className="crm-preview-row" key={row[1]}><span className="ui-person"><i>{row[0]}</i><b>{row[1]}</b></span><em>{row[2]}</em><strong>{row[3]}</strong></div>)}</div>;
  if (type === "extension") return <div className="product-ui browser-ui"><div className="browser-address"><span/><span/><span/><p>instagram.com/maya_creates</p></div><div className="social-profile"><i>MK</i><strong>Maya Kapoor</strong><small>Wellness creator · Mumbai</small></div><aside><header><Logo/><span>Connected</span></header><small>QA Agency workspace</small><div className="match-state"><BadgeCheck size={16}/><span><b>Profile matched</b><small>Already saved to Creator CRM</small></span></div><button>Open saved creator <ArrowRight size={14}/></button></aside></div>;
  return <div className="product-ui campaign-ui"><header><span>Campaigns</span><button>+ Create campaign</button></header><div className="campaign-tabs"><span>All campaigns <b>8</b></span><span className="selected">Northstar Foods <b>3</b></span><span>Aperture Labs <b>2</b></span></div><div className="campaign-card-preview"><small>Northstar Foods</small><strong>Festive creator launch</strong><p>Drive consideration with trusted lifestyle creators.</p><footer><span><Users size={13}/> 12 creators</span><span>INR 500,000</span></footer></div></div>;
}

export function LandingPage({ navigate }: { navigate(route: AppRoute): void }) {
  const startFree = () => navigate({ name: "signup" });
  return <main className="home-page">
    <header className="home-nav"><Logo/><nav aria-label="Landing navigation"><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#addons">Add-ons</a><button onClick={() => navigate({ name: "pricing" })}>Pricing</button></nav><div className="home-nav-actions"><button className="text-button" onClick={() => navigate({ name: "login" })}>Log in</button><button className="button button-primary" onClick={startFree}>Start free</button></div></header>
    <section className="home-hero" aria-labelledby="home-title"><div className="home-hero-copy"><p className="home-kicker"><Sparkles size={14}/> Creator operations for agencies and brands</p><h1 id="home-title">Find the right creators. Run the whole campaign.</h1><p>Creatorly combines creator discovery, your private CRM, browser research, and campaign execution in one workspace built for influencer marketing teams.</p><div className="home-hero-actions"><button className="button button-primary" onClick={startFree}>Start your creator workspace <ArrowRight size={17}/></button><a href="#workflow">See how it works</a></div><div className="home-trust"><span><Check size={14}/> 25 credits included</span><span><Check size={14}/> No card needed</span><span><Check size={14}/> Private workspace data</span></div></div><div className="home-operating-rail" aria-label="Creatorly product workflow"><header><span>Campaign operating rail</span><small>One connected workspace</small></header>{products.map(({ number, icon: Icon, name }, index) => <div className="operating-step" key={name}><code>{number}</code><span><Icon size={17}/></span><strong>{name}</strong>{index < products.length - 1 ? <ArrowRight size={15}/> : <BadgeCheck size={16}/>}</div>)}<footer><span><b>12</b> shortlisted</span><span><b>8</b> contacted</span><span><b>4</b> in review</span><span><b>3</b> live</span></footer></div></section>
    <section className="home-audience" aria-label="Built for creator partnership teams"><p>Built for teams running creator partnerships</p><div><span>Influencer agencies</span><span>Consumer brands</span><span>Creator marketing teams</span><span>Talent partners</span></div></section>
    <section className="home-products" id="platform"><header className="home-section-head"><p className="eyebrow">The product today</p><h2>One workspace from discovery to delivery.</h2><p>Start with Creatorly’s data. Add the creator relationships your team already owns. Keep the campaign moving without losing context between tools.</p></header>{products.map(({ number, icon: Icon, name, title, body, points, visual }, index) => <article className={`home-product-row ${index % 2 ? "reverse" : ""}`} id={index === 0 ? "workflow" : undefined} key={name}><div className="home-product-copy"><span className="product-number">{number}</span><div className="product-name"><Icon size={18}/>{name}</div><h3>{title}</h3><p>{body}</p><ul>{points.map(point => <li key={point}><Check size={14}/>{point}</li>)}</ul></div><div className="home-product-stage"><ProductVisual type={visual}/></div></article>)}</section>
    <section className="home-addons" id="addons"><header><div><p className="eyebrow">Future add-ons</p><h2>More automation when your workflow is ready for it.</h2></div><p>These products are on the roadmap and are not represented as live features in the current build.</p></header><div>{addons.map(({ icon: Icon, title, body }) => <article key={title}><span><Icon size={19}/></span><div><small>Future add-on</small><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
    <section className="home-final"><span><FolderKanban size={18}/> Your creator workspace starts here</span><h2>Bring creator discovery, relationships, and campaign work together.</h2><p>Create a free workspace and start with the features available today.</p><button className="button" onClick={startFree}>Start your creator workspace <ArrowRight size={18}/></button></section>
    <footer className="home-footer"><Logo/><span>© 2026 Creatorly · Creator operations for agencies and brands</span><nav aria-label="Footer navigation"><a href="#platform">Platform</a><a href="#addons">Future add-ons</a><button onClick={() => navigate({ name: "pricing" })}>Pricing</button></nav></footer>
  </main>;
}
