import { Bell, Puzzle, ShieldCheck, UserRound } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useAppData } from "../data/AppData";
import type { NotificationPreferences, Viewer } from "../types";

export function SettingsView({ viewer, refresh }: { viewer: Viewer; refresh(): void }) {
  const data = useAppData(); const [message, setMessage] = useState(""); const [extensionToken, setExtensionToken] = useState(""); const [preferences, setPreferences] = useState<NotificationPreferences>(viewer.notificationPreferences);
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await data.updateProfile({ name: String(form.get("name")), companyName: String(form.get("companyName")), phone: String(form.get("phone")) || undefined }); refresh(); setMessage("Profile saved."); }
  async function savePreferences() { await data.updateNotifications(preferences); refresh(); setMessage("Notification preferences saved."); }
  return <main className="workspace settings-workspace"><header className="settings-intro"><p className="eyebrow">Workspace settings</p><h1>Keep your contact desk current.</h1><p>Update your profile, alerts, extension connection, and subscription.</p></header>{message ? <div className="settings-message" role="status">{message}</div> : null}
    <div className="settings-grid"><section className="settings-section"><header><UserRound/><div><h2>Profile</h2><p>Shown in your Creatorly workspace.</p></div></header><form onSubmit={saveProfile}><label><span>Full name</span><input name="name" defaultValue={viewer.name} required/></label><label><span>Agency name</span><input name="companyName" defaultValue={viewer.companyName} required/></label><label><span>Email</span><input value={viewer.email} disabled/></label><label><span>Phone</span><input name="phone" type="tel" defaultValue={viewer.phone}/></label><button className="button button-primary">Save profile</button></form></section>
    <section className="settings-section"><header><Bell/><div><h2>Email notifications</h2><p>Choose which reminders Creatorly should send.</p></div></header><div className="toggle-list">{([{ key:"requestFulfilled", label:"Requested contact is available" },{ key:"lowBalance",label:"Credit balance is low"},{key:"expirationWarning",label:"Access expires within 24 hours"},{key:"weeklySummary",label:"Weekly usage summary"}] as const).map(item => <label key={item.key}><span><strong>{item.label}</strong><small>{item.key === "weeklySummary" ? "A weekly account recap." : "Only sent when action is useful."}</small></span><input type="checkbox" checked={preferences[item.key]} onChange={e => setPreferences(p => ({ ...p, [item.key]: e.target.checked }))}/></label>)}</div><button className="button button-primary" onClick={savePreferences}>Save notifications</button><p className="provider-note">Email delivery is simulated until an email provider is connected. Fulfilment alerts also appear in the app.</p></section>
    <section className="settings-section"><header><Puzzle/><div><h2>Chrome extension</h2><p>Use Creatorly on creator profile pages.</p></div></header><ol className="install-steps"><li>Open <code>chrome://extensions</code>.</li><li>Turn on Developer mode.</li><li>Choose Load unpacked and select the repository’s <code>extension</code> folder.</li><li>Create a connection key below and paste it into the extension popup.</li></ol>{extensionToken ? <div className="extension-key"><code>{extensionToken}</code><button className="button button-secondary" onClick={async()=>{await navigator.clipboard.writeText(extensionToken);setMessage("Extension connection key copied.");}}>Copy key</button></div> : <button className="button button-primary" onClick={async()=>{const result=await data.createExtensionToken();setExtensionToken(result.token);}}>Create connection key</button>}<p className="provider-note">Creating a new key revokes the previous one. Treat it like a password.</p></section>
    <section className="settings-section"><header><ShieldCheck/><div><h2>Security</h2><p>Password and subscription controls.</p></div></header><div className="security-row"><span><strong>Password</strong><small>Password reset email is not connected yet.</small></span><button className="button button-secondary" onClick={() => setMessage("Password reset needs an email provider. No account changes were made.")}>Request reset</button></div>{viewer.currentPlanTier !== "free" ? <div className="danger-zone"><strong>Cancel subscription</strong><p>Your plan remains available until the renewal date. DemoPay will not renew it.</p><button className="button button-danger" onClick={async () => { await data.requestCancellation(); refresh(); setMessage("Subscription cancelled at the end of the current demo period."); }}>Cancel plan</button></div> : null}</section></div>
  </main>;
}
